import type { CommandPlacement } from "./command-registry-types.js";

export const COMMAND_PLACEMENTS = [
    { commandId: "install_runtime", section: "home", order: 1, label: "Prepare repo" },
    { commandId: "open_config_editor", section: "home", order: 2, label: "Choose defaults" },
    { commandId: "preview_codex_profile", section: "home", order: 3, label: "Preview Codex settings" },
    { commandId: "backup_codex_config", section: "home", order: 4, label: "Save rollback point" },
    { commandId: "apply_codex_profile", section: "home", order: 5, label: "Apply Codex settings" },
    { commandId: "export_all", section: "home", order: 6, label: "Install Codex add-ons" },
    { commandId: "doctor", section: "home", order: 7, label: "Run health check" },
    { commandId: "open_config_editor", section: "settings", order: 1, label: "Model defaults" },
    { commandId: "open_pack_editor", section: "settings", order: 2, label: "Guidance options" },
    { commandId: "open_privacy_editor", section: "settings", order: 3, label: "Privacy" },
    { commandId: "show_config", section: "settings", order: 4, label: "Local Sane config" },
    { commandId: "show_codex_config", section: "settings", order: 5, label: "Codex config" },
    { commandId: "preview_statusline_profile", section: "settings", order: 6, label: "Preview statusline" },
    { commandId: "apply_statusline_profile", section: "settings", order: 7, label: "Apply statusline settings" },
    { commandId: "preview_cloudflare_profile", section: "settings", order: 8, label: "Cloudflare preview" },
    { commandId: "apply_cloudflare_profile", section: "settings", order: 9, label: "Apply Cloudflare" },
    { commandId: "toggle_auto_updates", section: "settings", order: 10, label: "Auto updates" },
    { commandId: "export_all", section: "add_to_codex", order: 1, label: "Install personal setup" },
    { commandId: "export_user_skills", section: "add_to_codex", order: 2, label: "Install Sane skills" },
    { commandId: "export_global_agents", section: "add_to_codex", order: 3, label: "Install global guidance" },
    { commandId: "export_custom_agents", section: "add_to_codex", order: 4, label: "Install named agents" },
    { commandId: "export_hooks", section: "add_to_codex", order: 5, label: "Install hooks" },
    { commandId: "apply_integrations_profile", section: "add_to_codex", order: 6, label: "Tool setup" },
    { commandId: "export_repo_skills", section: "add_to_codex", order: 7, label: "Repo skills" },
    { commandId: "export_repo_agents", section: "add_to_codex", order: 8, label: "Repo guidance" },
    { commandId: "export_opencode_all", section: "add_to_codex", order: 9, label: "Install OpenCode setup" },
    { commandId: "show_status", section: "status", order: 1, label: "Overall health" },
    { commandId: "doctor", section: "status", order: 2, label: "Run health check" },
    { commandId: "show_runtime_summary", section: "status", order: 3, label: "Handoff notes" },
    { commandId: "show_config", section: "status", order: 4, label: "Local Sane config" },
    { commandId: "show_codex_config", section: "status", order: 5, label: "Codex config" },
    { commandId: "preview_integrations_profile", section: "status", order: 6, label: "Tool setup preview" },
    { commandId: "preview_statusline_profile", section: "status", order: 7, label: "Statusline preview" },
    { commandId: "preview_policy", section: "status", order: 8, label: "Routing preview" },
    { commandId: "check_updates", section: "status", order: 9, label: "Check for updates" },
    { commandId: "install_runtime", section: "repair", order: 1, label: "Repair local files" },
    { commandId: "backup_codex_config", section: "repair", order: 2, label: "Back up Codex config" },
    { commandId: "restore_codex_config", section: "repair", order: 3, label: "Restore Codex backup" },
    { commandId: "reset_telemetry_data", section: "repair", order: 4, label: "Clear telemetry" },
    { commandId: "uninstall_user_skills", section: "uninstall", order: 1, label: "Remove user skills" },
    { commandId: "uninstall_global_agents", section: "uninstall", order: 2, label: "Remove global guidance" },
    { commandId: "uninstall_hooks", section: "uninstall", order: 3, label: "Remove hooks" },
    { commandId: "uninstall_custom_agents", section: "uninstall", order: 4, label: "Remove named agents" },
    { commandId: "uninstall_repo_skills", section: "uninstall", order: 5, label: "Remove repo skills" },
    { commandId: "uninstall_repo_agents", section: "uninstall", order: 6, label: "Remove repo guidance" },
    { commandId: "uninstall_all", section: "uninstall", order: 7, label: "Remove all Sane add-ons" }
  ] satisfies CommandPlacement[];
